### ISSUE TITLE
The client area of the window extends beyond the title bar on scaled displays.

### ISSUE THREAD

**Issue by huangfuyu** [ColleagueRiley/RGFW#113]
"I have two screens. The window displays correctly on the main screen, but the client area appears abnormal on the secondary screen. The resolutions of the two screens are different."

This is the image of the main screen.
![Image](https://github.com/user-attachments/assets/03a5d1fc-0fab-4640-9348-d5dcd2747a33)

This is the image of the secondary screen.
![Image](https://github.com/user-attachments/assets/4a1226d0-a2ab-4a45-9a35-3fc7c78bf1b1)

**Comment by ColleagueRiley** [comment]
That's very strange. I can't seem to recreate that with my current setup. Could you tell me the resolutions of your monitors and which one is the primary monitor?

**Comment by huangfuyu** [comment]
Got it. The issue above occurs when the scaling ratios of my two screens are different.
The scaling and layout of my primary screen is set to 125%, while the secondary screen is set to 100%.

**Comment by ColleagueRiley** [comment]
Ah, I figured it had something to do with scaling. I'll test that.

The title bar should still be scaled with the content, so this is still a strange bug to me.

**Comment by ColleagueRiley** [comment]
The buffers and portable GL examples don't have this issue.

**Comment by ColleagueRiley** [comment]
It seems like it's related to the `RGFW_windowNoResize` flag.

**Comment by huangfuyu** [comment]
> 缓冲区和便携式 GL 示例没有这个问题。

On my computer, the issue still persists.

![Image](https://github.com/user-attachments/assets/3231f017-4a1a-4e19-a0a7-ddcb2cc64bda)

![Image](https://github.com/user-attachments/assets/808b707f-494a-4127-88dd-77ca09c17dc6)

**Comment by ColleagueRiley** [comment]
I suppose that makes sense. If `RGFW_windowNoResize` seems to be a high-level cause of the issue.

**Comment by ColleagueRiley** [comment]
This problem also occurs for `examples/basic/basic`, so it's not just a software rendering issue.

![Image](https://github.com/user-attachments/assets/b76c8c91-7611-4f7c-b7bc-725c2dc88042)

**Comment by ColleagueRiley** [comment]
This only happens when the `RGFW_windowNoResize` flag is applied.

It is strange that in your screenshot, the `examples/buffer/buffer` example has this issue. When it doesn't use that flag.

**Comment by ColleagueRiley** [comment]
It seems that `RGFW_windowNoResize` made it so the window didn't include the `WS_THICKFRAME` flag. 

This issue should be fixed with the latest commits.

**Comment by huangfuyu** [comment]
Unfortunately, this problem still exists on my computer.
![Image](https://github.com/user-attachments/assets/d85decc5-65ae-46c3-bde2-6c7ad4729430)

**Comment by ColleagueRiley** [comment]
I'm unable to replicate the bug. 

(On the larger 1920x1080 primary screen with 125% scaling.)

![Image](https://github.com/user-attachments/assets/654801f9-7068-4357-b0e7-a7ca868bb910)

(On the smaller 1366x765 secondary screen with 100% scaling)

![Image](https://github.com/user-attachments/assets/31262ac8-c2e3-4cfc-89ca-d88c406bf919)

With extended displays, both in landscape mode. 

Can you give other information about the monitors to help recreate the bug?

**Comment by huangfuyu** [comment]
My two screens both have a resolution of 1920×1080, but the main screen is set to 125% scaling, while the secondary screen is set to 100% scaling.

![Image](https://github.com/user-attachments/assets/5e08edd7-128e-4415-b65a-22551bdecf9f)

![Image](https://github.com/user-attachments/assets/5d66ffb8-b9c8-4e53-ad23-e8cad76a2bd4)

**Comment by ColleagueRiley** [comment]
I was able to test the same monitor arrangement and I was still unable to recreate the issue. 

Are you sure that was done using the newest version of RGFW?

**Comment by ColleagueRiley** [comment]
I'm closing this issue because it has been unable to be recreated and it has been left stagnant for some time. 

If there are any updates or anyone is able to recreate this issue, please reopen this issue or file a new one.
