### ISSUE TITLE
X11 window does not close properly on some systems

### ISSUE THREAD

**Issue by EimaMei** [ColleagueRiley/RGFW#21]
While all of the RGFW examples through the base Makefile compile just fine on LInux, quite a few of them do not work as intended at all.

**Crashes/Do not run**
Trying to run the `vk10` example on Linux results in a segmentation fault, while trying to run `basic` results in the window being opened for a few frames before closing the window entirely. While I'm not sure as to why `vk10` crashes (I do not use or know to use Vulkan), the `basic` example has a very silly issue, where the while loop only continues if the escape key is being pressed
```c
while (running && RGFW_isPressed(win, RGFW_Escape)) {   
```
Add a `!` unary operator before the function or a simple `<function> == 0` comparison fixes this.

**Cannot exit**
Both `events` and `callbacks` suffer from the same issue of not being able to cleanly exit the app without forcing an exit via external means. To me my limited understanding this happens because the `RGFW_window_shouldClose` function doesn't catch the `RGFW_quit` for ??? reasons. Perhaps some other event replaces the `.type` member when the loop cycle is finished? I'm not sure exactly what's going on.

**Unintended behaviour**
The `camera` example goes absolutely crazy on my system:

https://github.com/ColleagueRiley/RGFW/assets/69605234/dff9feac-b160-497f-8de1-7d0734c7aec9

My theory as to why this happens is because that kind of effect (effect being seeing all of the windows and being able to select one) is achieved on KDE by moving the mouse cursor to the top left position. Thus, `RGFW_window_mouseHold` may be continuously moving the cursor to the `(0 ,0)` coordinates by mistake, even though looking at the source that shouldn't really happen.

**Comment by ColleagueRiley** [comment]
> the basic example has a very silly issue, where the while loop only continues if the escape key is being pressed
this has been fixed

> Trying to run the vk10 example on Linux results in a segmentation fault

I believe this is a driver issue
![image](https://github.com/ColleagueRiley/RGFW/assets/50218871/974975a4-f3b6-43cd-bfe2-4943f966a0ac)

> Cannot exit

this issue doesn't happen anymore, maybe it was fixed after the issue and I didn't notice

> Unintended behaviour
Please move this to a separate issue because this is about support for a specific DE rather than linux support in general. The code works on Manjaro Xfce, so I assume KDE handles mouse stuff differently.

**Comment by EimaMei** [comment]
While it most definitely is a driver issue, it does seem to me that either RGFW internally or the example itself is doing something that causes the app to crash when being it’s being ran. Because of that it would be best if somehow that issue were to be fixed, albeit I recognise that it most likely isn’t feasible for you to try and figure out what’s causing the issue when the example works on your machine just fine.

As for the camera example, I find it to be a bit silly to assume that “KDE handles mouse stuff differently” purely because of your example only working on XFCE (implying that RGFW’s code on achieving a first person camera is somewhat of a hack and thus, needs more attention). It’s also weird waving this off as “not general Linux support” considering RGFW functionality is broken on one of the most popular DEs on Linux, but I digress. Since every other example (minus the Vulkan one somewhat) is fixed, it wouldn’t mind renaming this issue to reflect the current status of it.

**Comment by ColleagueRiley** [comment]
@EimaMei the issue is specifically with the RGFW_window_moveMouse function, you must do this for the mouse to move (on xfce)

```c
		XWarpPointer(win->src.display, None, None, 0, 0, 0, 0, -event.xbutton.x, -event.xbutton.y);
		XWarpPointer(win->src.display, None, None, 0, 0, 0, 0, v.x, v.y);
```

I don't know how it's supposed to be done for KDE, I'll refer to GLFW's code. 

As for FPS movement being a hack: it is, this is because X11 has no actual system for locking the mouse to the window as far as I know, and most systems settle with moving it to the middle of the screen.

**Comment by ColleagueRiley** [comment]
@EimaMei The cursor move function should work now on both DEs

**Comment by EimaMei** [comment]
`camera` and `basic` now work for me but `events` and `callbacks` still have the same issue. Quitting the application only prints 'Quit' and closes the window, but doesn't stop the while loop from continuously running
